name: Test Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testbed:
    name: Testbed - ${{ matrix.wm.name }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04
    strategy:
      fail-fast: false
      matrix:
        wm:
          - name: x11
            pkg: blackbox
            start: |
              echo "Start window manager..."
              DISPLAY=:99 blackbox &
              sleep 1
            runenv: DISPLAY=:99
          # dbus-x11 provides dbus-launch even though we're doing
          # wayland stuff here
          - name: wayland
            pkg: mutter dbus-x11
            start: |
              echo "Set up dbus..."
              eval "$(dbus-launch --sh-syntax)"
              sleep 1
              echo "Set up XDG_RUNTIME_DIR..."
              export XDG_RUNTIME_DIR=/tmp/runtime-$USER
              mkdir -p $XDG_RUNTIME_DIR
              chmod 700 $XDG_RUNTIME_DIR
              echo "Start Window Manager..."
              DISPLAY=:99 MUTTER_DEBUG_DUMMY_MODE_SPECS=2048x1536 \
                  mutter --nested --wayland --no-x11 --wayland-display toga &
              sleep 1
            runenv: WAYLAND_DISPLAY=toga

    steps:
      - name: actions/checkout issue 363 workaround
        run: |
          apt update
          apt-get install -y git
          git config --global --add safe.directory $PWD

      - name: Check out repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          apt-get install -y ${{ matrix.wm.pkg }} python3 xvfb python3-pip breeze
          apt-get install -y \
            python3-pyside6.qtcore \
            python3-pyside6.qtwidgets \
            python3-pyside6.qtgui \
            python3-pyside6.qtquickwidgets
          alias python="python3"
          python -m pip install --break-system-packages git+https://github.com/beeware/briefcase.git

      - name: Testing
        run: |
          export QT_STYLE_OVERRIDE=Breeze

          echo "Start X server..."
          Xvfb :99 -screen 0 2048x1536x24 &
          sleep 1

          # Start window manager depending on matrix value
          ${{ matrix.wm.start }}

          ./update-testbed.sh
          cd testbed
          ${{ matrix.wm.runenv }} briefcase run linux --log --test -- \
            tests/app/ tests/window/ tests/test_command.py \
            tests/test_keys.py tests/test_paths.py \
            tests/widgets/test_button.py tests/widgets/test_box.py \
            tests/widgets/test_base.py tests/widgets/test_textinput.py \
            tests/widgets/test_label.py tests/widgets/test_activityindicator.py \
            tests/test_fonts.py tests/test_images.py \
            --ci
