name: Test Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testbed:
    name: Testbed - ${{ matrix.wm.name }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04
    strategy:
      matrix:
        wm:
          - name: x11
            pkg: openbox
            start: |
              echo "Start window manager..."
              DISPLAY=:99 openbox &
              sleep 1
            runenv: DISPLAY=:99
          - name: wayland
            pkg: mutter
            start: |
              echo "Start Window Manager..."
              DISPLAY=:99 MUTTER_DEBUG_DUMMY_MODE_SPECS=2048x1536 \
                  mutter --nested --wayland --no-x11 --wayland-display toga &
              sleep 1
            runenv: WAYLAND_DISPLAY=toga

    steps:
      - name: actions/checkout issue 363 workaround
        run: |
          apt update
          apt-get install -y git
          git config --global --add safe.directory $PWD

      - name: Check out repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          apt-get install -y ${{ matrix.wm.pkg }} python3 xvfb python3-pip breeze
          apt-get install -y \
            libpyside6-dev \
            libpyside6-py3-6.8 \
            libshiboken6-dev \
            libshiboken6-py3-6.8 \
            pyside6-tools \
            python-pyside6-doc \
            shiboken6 \
            shiboken6-doc \
            "python3-pyside6.*"
          alias python="python3"
          python -m pip install --break-system-packages git+https://github.com/beeware/briefcase.git

      - name: Testing
        run: |
          export QT_STYLE_OVERRIDE=Breeze

          echo "Start X server..."
          Xvfb :99 -screen 0 2048x1536x24 &
          sleep 1

          # Start window manager depending on matrix value
          ${{ matrix.wm.start }}

          ./update-testbed.sh
          cd testbed
          ${{ matrix.wm.runenv }} briefcase run linux --log --test -- \
            tests/app/ tests/window/ tests/test_command.py \
            tests/test_keys.py tests/test_paths.py \
            tests/widgets/test_button.py tests/widgets/test_box.py \
            tests/widgets/test_base.py --ci
